"""Shared metric/report column names."""

K = "k"
SCALE_MINUTES = "scale_minutes"
SCALE_DAYS = "scale_days"

ENERGY = "energy"
RMS_VOLATILITY = "rms_volatility"
ANNUALIZED_RMS_VOLATILITY = "annualized_rms_volatility"
DETAIL_ENERGY_SHARE = "detail_energy_share"
TOTAL_COMPONENT_ENERGY_SHARE = "total_component_energy_share"

REPEAT_LENGTH = "repeat_length"
EFFECTIVE_N = "effective_n"
ORDINAL_WINDOWS = "ordinal_windows"
PERMUTATION_ENTROPY = "permutation_entropy"
NORMALIZED_ENTROPY = "normalized_entropy"
FINAL_NORMALIZED_ENTROPY = "final_normalized_entropy"
SHUFFLE_NORMALIZED_ENTROPY = "shuffle_normalized_entropy"
GAUSSIAN_NORMALIZED_ENTROPY = "gaussian_normalized_entropy"
ENTROPY_GAP_SHUFFLE = "entropy_gap_shuffle"
ENTROPY_GAP_GAUSSIAN = "entropy_gap_gaussian"

ORIGINAL_ENERGY = "original_energy"
DETAIL_ENERGY_SUM = "detail_energy_sum"
APPROXIMATION_ENERGY = "approximation_energy"
TOTAL_COMPONENT_ENERGY = "total_component_energy"
ENERGY_RECONSTRUCTION_GAP = "energy_reconstruction_gap"
DETAIL_ENERGY_SHARE_SUM = "detail_energy_share_sum"
TOTAL_COMPONENT_ENERGY_SHARE_SUM = "total_component_energy_share_sum"

