"""Expected input and output schemas for pipeline artifacts."""

from __future__ import annotations

from multi_scale_volatility.config.columns import (
    COMPONENT,
    COMPONENT_TYPE,
    INDEX,
    LOG_RETURN,
    ORIGINAL,
    SERIES,
    TIMESTAMP_UTC,
)
from multi_scale_volatility.config.metric_columns import (
    ANNUALIZED_RMS_VOLATILITY,
    DETAIL_ENERGY_SHARE,
    EFFECTIVE_N,
    ENERGY,
    ENTROPY_GAP_GAUSSIAN,
    ENTROPY_GAP_SHUFFLE,
    FINAL_NORMALIZED_ENTROPY,
    GAUSSIAN_NORMALIZED_ENTROPY,
    K,
    NORMALIZED_ENTROPY,
    ORDINAL_WINDOWS,
    PERMUTATION_ENTROPY,
    REPEAT_LENGTH,
    RMS_VOLATILITY,
    SCALE_DAYS,
    SCALE_MINUTES,
    SHUFFLE_NORMALIZED_ENTROPY,
    TOTAL_COMPONENT_ENERGY_SHARE,
)

RETURN_COLUMNS = (TIMESTAMP_UTC, LOG_RETURN)
DECOMPOSITION_BASE_COLUMNS = (INDEX, TIMESTAMP_UTC, ORIGINAL)

METRIC_INDEX_COLUMNS = (
    COMPONENT,
    K,
    COMPONENT_TYPE,
    SCALE_MINUTES,
    SCALE_DAYS,
)
ENTROPY_GAP_INDEX_COLUMNS = (*METRIC_INDEX_COLUMNS, REPEAT_LENGTH)

VOLATILITY_COLUMNS = (
    SERIES,
    *METRIC_INDEX_COLUMNS,
    ENERGY,
    DETAIL_ENERGY_SHARE,
    TOTAL_COMPONENT_ENERGY_SHARE,
    RMS_VOLATILITY,
    ANNUALIZED_RMS_VOLATILITY,
)

LAYER_ENTROPY_COLUMNS = (
    SERIES,
    *ENTROPY_GAP_INDEX_COLUMNS,
    EFFECTIVE_N,
    ORDINAL_WINDOWS,
    PERMUTATION_ENTROPY,
    NORMALIZED_ENTROPY,
)

ENTROPY_GAP_COLUMNS = (
    *ENTROPY_GAP_INDEX_COLUMNS,
    FINAL_NORMALIZED_ENTROPY,
    SHUFFLE_NORMALIZED_ENTROPY,
    GAUSSIAN_NORMALIZED_ENTROPY,
    ENTROPY_GAP_SHUFFLE,
    ENTROPY_GAP_GAUSSIAN,
)


def decomposition_columns(
    components: list[str] | tuple[str, ...],
    include_timestamp: bool = True,
) -> tuple[str, ...]:
    base = DECOMPOSITION_BASE_COLUMNS if include_timestamp else (
        INDEX, ORIGINAL)
    return (*base, *components)
